# Generated by Django 3.0.8 on 2020-12-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201210_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='email address'),
        ),
    ]
