# Generated by Django 3.0.8 on 2020-12-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201211_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='session_token',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
